<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'User ID' => 'Идентификатор',
    'Login' => 'Логин',
    'Password' => 'Пароль',
    'Email' => 'Почта',
    'Phone' => 'Телефон',
    'Create User' => 'Создать пользавателя',
    'Users' => 'Пользователи',
    'User Status' => 'Статус пользователя',
    'Confirm your email address' => 'Потверждение электронный почты',
    'Active' => 'Активный',
    'Off' => 'Отключён',
    'Blocked' => 'Заблокирован',
    'Update' => 'Обновить',
    'Delete' => 'Удалить',
    'Are you sure you want to delete this item?' => 'Вы уверены что хотите удалить пользователя?',
    'Update User' => 'Обновление пользователя',
    'Save' => 'Сохранить',
    'Create Users' => 'Создание пользователя',
    'Thanks for the information about of error!' => 'Спасибо за оповешение об ошибки!',
    'Your email is confirmed successfully!' => 'Ваша электронная почта успешно потверждена!',
    'Create Tokens' => 'Создание токена',
    'Tokens' => 'Токены',
    'Update Tokens' => 'Обновление токена',
    'singin' => 'Вход',
    'login now' => 'Войти',
    'Logout' => 'Выйти',
];
