<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Confirm email' => 'Confirm email',
    'New Password Create' => 'New Password Create',
    'User ID' => 'User ID',
    'Login' => 'Login',
    'Password' => 'Password',
    'Email' => 'Email',
    'Phone' => 'Phone',
    'Create User' => 'Create User',
    'Users' => 'Users',
    'User Status' => 'User Status',
    'Confirm your email address' => 'Confirm your email address',
    'Thanks for the information about of error!' => 'Thanks for the information about of error!',
    'Active' => 'Active',
    'Off' => 'Off',
    'Blocked' => 'Blocked',
    'Update' => 'Update',
    'Delete' => 'Delete',
    'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
    'Update User' => 'Update User',
    'Save' => 'Save',
    'Create Users' => 'Create Users',
    'Your email is confirmed successfully!' => 'Your email is confirmed successfully!',
    'Create Tokens' => 'Create Tokens',
    'Tokens' => 'Tokens',
    'Update Tokens' => 'Update Tokens',
    'singin' => 'Login',
    'login now' => 'Login',
    'Logout' => 'Logout',

];
