<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'User ID' => 'Identifikatori',
    'Login' => 'Login',
    'Password' => 'Maxfiy kalit',
    'Email' => 'Elektron quti',
    'Phone' => 'Telefon',
    'Create User' => 'Foydalanuvchini yaratish',
    'Users' => 'Foydalanuvchilar',
    'User Status' => 'Foydalanuvchi holati',
    'Confirm your email address' => 'Elektron qutini tasdiqlash',
    'Active' => 'Aktiv',
    'Off' => 'O`chirilgan',
    'Blocked' => 'Bloklangan',
    'Update' => 'Yangilash',
    'Delete' => 'O`chirish',
    'Are you sure you want to delete this item?' => 'Aniqmi?',
    'Update User' => 'Foydalanuvchini yangilash',
    'Save' => 'Saqlash',
    'Create Users' => 'Foydalanuvchini yaratish',
    'Thanks for the information about of error!' => 'Hatolik haqida bizga habar berganingiz uchun raxmat!',
    'Your email is confirmed successfully!' => 'Sizning elektron qutingiz tasdiqlandi!',
    'Create Tokens' => 'Token yaratish',
    'Tokens' => 'Tokenlar',
    'Update Tokens' => 'Token yangilash',
    'singin' => 'Kirish',
    'login now' => 'Kirish',
    'Logout' => 'Chiqish',
];
